"""
ITP file writing module for CTGoMartini.

Provides functionality for writing GROMACS ITP (Include Topology) files
from molecule objects.
"""

from __future__ import annotations

import re
from typing import Any


def write_itp(
    mol: Any,
    itp_file: str = 'default',
    params_file: str = 'default'
) -> None:
    """
    Write GROMACS ITP (Include Topology) files for a molecule.
    
    Generates two ITP files:
    1. Main topology file containing molecule structure and interactions
    2. Parameters file containing atom type definitions
    
    Args:
        mol: Molecule object containing topology information.
            Must have _topology attribute with 'moleculetype' and 'atoms' keys.
        itp_file: Name of the main topology file.
            Default uses molecule name: "{molecule_name}.itp"
        params_file: Name of the parameters file.
            Default uses molecule name: "{molecule_name}_params.itp"
    """
    # Extract molecule name from topology data
    molecule_name: str = mol._topology['moleculetype'][0][0]
    
    # Set default filenames if not provided
    if itp_file == 'default':
        itp_file = f'{molecule_name}.itp'
    if params_file == 'default':
        params_file = f'{molecule_name}_params.itp'
    
    # Generate main ITP file content
    itp_lines: list[str] = []
    
    # Add header comment
    itp_lines += ['; This file was generated by CTGoMartini.\n', '\n']
    
    # Process each category in the topology
    for category, fields_list in mol._topology.items():
        # Skip empty categories
        if not fields_list:
            continue

        # Add category section header
        itp_lines.append(f'\n[ {category} ]\n')
        
        # Add column headers for specific multi-state categories
        if category == 'multi_angles':
            itp_lines.append(
                ';atomid1, atomid2, atomid3, n_states, state, functype, angle, k\n'
            )
        elif category == 'multi_dihedrals':
            itp_lines.append(
                ';atomid1, atomid2, atomid3, atomid4, n_states, state, '
                'functype, phi, k, n\n'
            )
        elif category == 'multi_contacts':
            itp_lines.append(
                ';atomid1, atomid2, n_states, state, functype, sigma, epsilon\n'
            )

        # Process each entry in the current category
        for fields in fields_list:
            line = ' ' + ' '.join(fields) + '\n'
            itp_lines.append(line)
        
    # Write the main ITP file
    with open(itp_file, 'w') as f:
        f.writelines(itp_lines)

    # Generate parameters file content
    params_lines: list[str] = []
    
    # Extract atom types from the atoms list
    atoms_list: list[list[str]] = mol._topology['atoms']
    
    # Find new atom types matching the molecule name pattern (e.g., "PROTEIN_1")
    pattern = rf'{re.escape(molecule_name)}_\d+'
    new_atomtypes = [
        item[1] for item in atoms_list 
        if re.fullmatch(pattern, item[1])
    ]
    
    # If new atom types found, add them to the parameters file
    if new_atomtypes:
        # Format: atomtype, mass, charge, ptype, sigma, epsilon
        new_atomtypes_list = [
            [atomtype, '0.0', '0.0', 'A', '0.0', '0.0']
            for atomtype in new_atomtypes
        ]
        
        params_lines.append('\n[ atomtypes ]\n')
        
        for fields in new_atomtypes_list:
            line = ' ' + ' '.join(fields) + '\n'
            params_lines.append(line)

    # Write the parameters file
    with open(params_file, 'w') as f:
        f.writelines(params_lines)

